{{- range $i, $app := .Values.cronjobs }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
spec: 
  schedule: {{ .schedule }}
  timeZone: {{ .timeZone }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .name }}
              image: "{{ .image.name }}:{{ .image.tag }}"
          restartPolicy: {{ .restartPolicy }}

{{- end -}}
