# {{- $env := .Values.env }}
{{- range $i, $app := .Values.apps }}

{{- if ((.ingress).enabled) -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # {{ if eq $env "Development" }}
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    # {{ end }}
spec:
  ingressClassName: nginx
  rules:
      {{- range $i, $host := .ingress.hosts }}
      - host: {{ .host }}
        http:
          paths:
            {{- toYaml .paths | nindent 12 }}
      {{ end }}

---

{{- end }}

{{ end -}}