apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduled-autoscaler-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hpa-role
rules:
  - apiGroups: ['autoscaling']
    resources: ['horizontalpodautoscalers']
    verbs: ['*']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpa-rolebinding
subjects:
  - kind: ServiceAccount
    name: scheduled-autoscaler-service-account
    namespace: voting-app
roleRef:
  kind: Role
  name: hpa-role
  apiGroup: rbac.authorization.k8s.io
