apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduled-autoscaler-service-account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-hpa-role
rules:
  - apiGroups: ['*']
    resources: ['horizontalpodautoscalers']
    verbs: ['*']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-hpa-rolebinding
subjects:
  - kind: ServiceAccount
    name: scheduled-autoscaler-service-account
    namespace: voting-app
roleRef:
  kind: ClusterRole
  name: cluster-hpa-role
  apiGroup: rbac.authorization.k8s.io
