apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-voting-app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hpa-role
rules:
  - apiGroups: ['']
    resources: ['horizontalpodautoscalers', 'pods']
    verbs: ['get', 'list', 'watch', 'update', 'patch']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpa-rolebinding

subjects:
  - kind: ServiceAccount
    name: sa-voting-app

roleRef:
  kind: Role
  name: hpa-role
  apiGroup: rbac.authorization.k8s.io
